apiVersion: v1
kind: Namespace
metadata:
  name: documentdb-preview-ns
---
apiVersion: v1
kind: Secret
metadata:
  name: documentdb-credentials
  namespace: documentdb-preview-ns
type: Opaque
stringData:
  username: k8s_secret_user     
  password: K8sSecret100  
---
apiVersion: documentdb.io/preview
kind: DocumentDB
metadata:
  name: documentdb-local-ha
  namespace: documentdb-preview-ns
spec:
  nodeCount: 1
  instancesPerNode: 3  # Creates 3 DocumentDB instances for HA
  documentDbCredentialSecret: documentdb-credentials
  resource:
    storage:
      pvcSize: 10Gi
  exposeViaService:
    serviceType: LoadBalancer